import {ClerkProvider} from '@clerk/nextjs'



import Header from "@/components/Header";
import "./globals.css";



export const metadata = {
  title: "Vesta",
  description: "Generated by Next js",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
     <ClerkProvider>
      <body>
          <Header/>
         {children}
       </body>
     </ClerkProvider>
    </html>
  );
}
